@echo off
rem OpenClaw Gateway (profile: desktop-stack, v2026.4.4)
set "OPENCLAW_GATEWAY_TOKEN=e7afbc173d37e4e4dea54999e31830e6bf7e44ff930ad880d69e2f1d594bc66e"
set "OLLAMA_API_KEY=ollama-local"
set "TELEGRAM_CHAT_ID=7201110294"
set "CLAWDBOT_GATEWAY_BIND=loopback"
set "CLAWDBOT_GATEWAY_MODE=local"
set "CLAWDBOT_GATEWAY_PORT=18789"
set "LINE_WEBHOOK_URL=https://remedial-joline-unrash.ngrok-free.dev/line/webhook"
set "OPENCLAW_BROWSER_URL=http://127.0.0.1:18789"
set "OPENCLAW_CONFIG_PATH=C:\Users\downl\Desktop\clawdbot-main3\clawdbot-main\.openclaw-desktop\openclaw.json"
set "OPENCLAW_DESKTOP_LAUNCHER=scripts/launchers/launch-desktop-stack.ps1"
set "OPENCLAW_GATEWAY_BIND=loopback"
set "OPENCLAW_GATEWAY_MODE=local"
set "OPENCLAW_GATEWAY_PORT=18789"
set "OPENCLAW_LOCAL_URL=http://127.0.0.1:18789"
set "OPENCLAW_PROFILE=desktop-stack"
set "OPENCLAW_PUBLIC_URL=https://remedial-joline-unrash.ngrok-free.dev"
set "OPENCLAW_STATE_DIR=C:\Users\downl\Desktop\clawdbot-main3\clawdbot-main\.openclaw-desktop"
set "TELEGRAM_WEBHOOK_URL=https://remedial-joline-unrash.ngrok-free.dev/telegram-webhook"
set "TELEGRAM_WEBHOOK_SECRET=4435630ad262f1da32229df74e7e5ad97f6542f095cf1fdcd81e76ccb114df30"
set "VOICEVOX_ENDPOINT=http://127.0.0.1:50021"
set "VOICEVOX_ENGINE_PATH=C:\Users\downl\AppData\Local\Programs\VOICEVOX\vv-engine\run.exe"
set "VOICEVOX_EXE_PATH=C:\Users\downl\AppData\Local\Programs\VOICEVOX\VOICEVOX.exe"
set "VOICEVOX_SPEAKER_ID=2"
set "NGROK_UPSTREAM_URL=http://127.0.0.1:8787"
set "NGROK_EXE=C:\ProgramData\chocolatey\bin\ngrok.exe"
set "HAKUA_HYPURA_GGUF=C:\Users\downl\Desktop\SO8T\gguf_models\stronman\Gemma-4-E4B-Uncensored-HauhauCS-Aggressive\Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-Q4_K_M.gguf"
set "HYPURA_PORT=8080"
set "HYPURA_CONTEXT=100000"
set "HAKUA_HYPURA_EXE=C:\Users\downl\Desktop\hypura-main\hypura-main\target\release\hypura.exe"
set "OPENCODE_API_KEY=sk-CirdvzUWG7IUtXs5OwMOrq7CngPwVgMF9Kf4pWB2TcS8jp23s8mRxkuFJ04Hx9wA"
set "HOME=C:\Users\downl"
set "TMPDIR=C:\Users\downl\AppData\Local\Temp"
set "OPENCLAW_SYSTEMD_UNIT=openclaw-gateway-desktop-stack.service"
set "OPENCLAW_WINDOWS_TASK_NAME=OpenClaw Gateway (desktop-stack)"
set "OPENCLAW_SERVICE_MARKER=openclaw"
set "OPENCLAW_SERVICE_KIND=gateway"
set "OPENCLAW_SERVICE_VERSION=2026.4.4"
if /I "%~1"=="repair-webhook" (
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Users\downl\Desktop\clawdbot-main3\clawdbot-main\scripts\launchers\repair-ngrok-and-telegram-webhook.ps1" -Port 18789 %2 %3 %4 %5 %6 %7 %8 %9
  goto :eof
)
"C:\Program Files\nodejs\node.exe" C:\Users\downl\Desktop\clawdbot-main3\clawdbot-main\dist\index.js gateway --port 18789
